# Form implementation generated from reading ui file 'acerca_de.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_wndAcercaDe(object):
    def setupUi(self, wndAcercaDe):
        wndAcercaDe.setObjectName("wndAcercaDe")
        wndAcercaDe.resize(588, 456)
        self.lblLogo = QtWidgets.QLabel(parent=wndAcercaDe)
        self.lblLogo.setGeometry(QtCore.QRect(20, 10, 211, 181))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("assets/img/logo.png"))
        self.lblLogo.setObjectName("lblLogo")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=wndAcercaDe)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 10, 299, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=wndAcercaDe)
        self.label_4.setGeometry(QtCore.QRect(120, 250, 381, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=wndAcercaDe)
        self.label_5.setGeometry(QtCore.QRect(80, 290, 491, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=wndAcercaDe)
        self.label_6.setGeometry(QtCore.QRect(200, 410, 201, 16))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(wndAcercaDe)
        QtCore.QMetaObject.connectSlotsByName(wndAcercaDe)

    def retranslateUi(self, wndAcercaDe):
        _translate = QtCore.QCoreApplication.translate
        wndAcercaDe.setWindowTitle(_translate("wndAcercaDe", "Acerca De"))
        self.label.setText(_translate("wndAcercaDe", "Sistema de visualizacion"))
        self.label_2.setText(_translate("wndAcercaDe", "de los Sectores criticos"))
        self.label_3.setText(_translate("wndAcercaDe", "de Sinestralidad vial"))
        self.label_4.setText(_translate("wndAcercaDe", "En este aplicativo podras encontrar los datos historicos de los sectores"))
        self.label_5.setText(_translate("wndAcercaDe", "criticos de sinestralidad vial en Colombia de 5 años (2015 - 2019) con siniestros fatales."))
        self.label_6.setText(_translate("wndAcercaDe", "© Daniel Niebles | Gianluca Brochero"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wndAcercaDe = QtWidgets.QWidget()
    ui = Ui_wndAcercaDe()
    ui.setupUi(wndAcercaDe)
    wndAcercaDe.show()
    sys.exit(app.exec())
