# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from windows.login import *
from windows.acercaDe import Ui_wndAcercaDe
from windows.registro import Ui_Registro


class Ui_HomeWindow(QtWidgets.QWidget):
    def __init__(self, userData):
        super().__init__()
        self.userData = userData

    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCloseSession = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCloseSession.setGeometry(QtCore.QRect(340, 420, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnCloseSession.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/img/close-session.png"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCloseSession.setIcon(icon)
        self.btnCloseSession.setObjectName("btnCloseSession")
        self.btnCloseSession.clicked.connect(self.closeSession)
        self.lblImg = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblImg.setGeometry(QtCore.QRect(300, 160, 221, 231))
        self.lblImg.setText("")
        self.lblImg.setPixmap(QtGui.QPixmap("assets/img/home.jpeg"))
        self.lblImg.setObjectName("lblImg")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("Bienvenido " + self.userData[1])
        self.label.setObjectName("label")
        HomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=HomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(parent=self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        HomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=HomeWindow)
        self.statusbar.setObjectName("statusbar")
        HomeWindow.setStatusBar(self.statusbar)
        self.actionInsertar = QtGui.QAction(parent=HomeWindow)
        self.actionInsertar.setObjectName("actionInsertar")
        self.actionInsertar.triggered.connect(self.gotoRegister)
        self.actionVisualizar = QtGui.QAction(parent=HomeWindow)
        self.actionVisualizar.setObjectName("actionVisualizar")
        self.actionAcerca_de = QtGui.QAction(parent=HomeWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionAcerca_de.triggered.connect(self.gotoAbout)
        self.menuMenu.addAction(self.actionInsertar)
        self.menuMenu.addAction(self.actionVisualizar)
        self.menuMenu.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "Home"))
        self.btnCloseSession.setText(_translate("HomeWindow", "Cerrar sesion"))
        self.menuMenu.setTitle(_translate("HomeWindow", "Menu"))
        self.actionInsertar.setText(_translate("HomeWindow", "Insertar"))
        self.actionVisualizar.setText(_translate("HomeWindow", "Visualizar"))
        self.actionAcerca_de.setText(_translate("HomeWindow", "Acerca de"))

    def closeSession(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_loginWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def gotoAbout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_wndAcercaDe()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def gotoRegister(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Registro()
        self.ui.setupUi(self.window)
        self.window.show()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeWindow = QtWidgets.QMainWindow()
    ui = Ui_HomeWindow()
    ui.setupUi(HomeWindow)
    HomeWindow.show()
    sys.exit(app.exec())
