# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from core.UserRepository import UserRepository
from windows.home import *


class Ui_loginWindow(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, loginWindow):
        self.loginWindow = loginWindow
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(782, 519)
        self.centralwidget = QtWidgets.QWidget(parent=loginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblLogin = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLogin.setGeometry(QtCore.QRect(580, 90, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblLogin.setFont(font)
        self.lblLogin.setObjectName("lblLogin")
        self.verticalLayoutWidget = QtWidgets.QWidget(
            parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(520, 150, 191, 216))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblUserName = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblUserName.setFont(font)
        self.lblUserName.setObjectName("lblUserName")
        self.verticalLayout.addWidget(self.lblUserName)
        self.txtUser = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtUser.setFont(font)
        self.txtUser.setObjectName("txtUser")
        self.verticalLayout.addWidget(self.txtUser)
        self.lblPassword = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPassword.setFont(font)
        self.lblPassword.setObjectName("lblPassword")
        self.verticalLayout.addWidget(self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(
            parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtPassword.setFont(font)
        self.txtPassword.setObjectName("txtPassword")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.verticalLayout.addWidget(self.txtPassword)
        self.btnLogin = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnLogin.clicked.connect(self.login)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLogin.setFont(font)
        icon = QtGui.QIcon.fromTheme("ok")
        self.btnLogin.setIcon(icon)
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout.addWidget(self.btnLogin)
        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(30, 80, 371, 78))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.lblTitle_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitle_2.setGeometry(QtCore.QRect(20, 160, 390, 78))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle_2.setFont(font)
        self.lblTitle_2.setObjectName("lblTitle_2")
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.frmLeft = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmLeft.setGeometry(QtCore.QRect(0, -10, 431, 511))
        self.frmLeft.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frmLeft.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frmLeft.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmLeft.setLineWidth(-1)
        self.frmLeft.setObjectName("frmLeft")
        self.label = QtWidgets.QLabel(parent=self.frmLeft)
        self.label.setGeometry(QtCore.QRect(100, 270, 201, 171))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/img/logo.png"))
        self.label.setObjectName("label")
        self.frmRigth = QtWidgets.QFrame(parent=self.centralwidget)
        self.frmRigth.setGeometry(QtCore.QRect(430, -20, 371, 521))
        self.frmRigth.setStyleSheet("background-color: rgb(177, 192, 200);")
        self.frmRigth.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frmRigth.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frmRigth.setObjectName("frmRigth")
        self.lblErrors = QtWidgets.QLabel(parent=self.frmRigth)
        self.lblErrors.setGeometry(QtCore.QRect(96, 420, 181, 20))
        self.lblErrors.setText("")
        self.lblErrors.setObjectName("lblErrors")
        self.frmRigth.raise_()
        self.frmLeft.raise_()
        self.lblLogin.raise_()
        self.verticalLayoutWidget.raise_()
        self.lblTitle.raise_()
        self.lblTitle_2.raise_()
        loginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=loginWindow)
        self.statusbar.setObjectName("statusbar")
        loginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate(
            "loginWindow", "Inicio de sesion"))
        self.lblLogin.setText(_translate("loginWindow", "Login"))
        self.lblUserName.setText(_translate("loginWindow", "Usuario:"))
        self.txtUser.setPlaceholderText(
            _translate("loginWindow", "Nombre de usuario"))
        self.lblPassword.setText(_translate("loginWindow", "Contraseña: "))
        self.txtPassword.setPlaceholderText(
            _translate("loginWindow", "Contraseña"))
        self.btnLogin.setText(_translate("loginWindow", "Iniciar Sesion"))
        self.lblTitle.setText(_translate(
            "loginWindow", "Sistema de visualizacion"))
        self.lblTitle_2.setText(_translate(
            "loginWindow", "de sectores criticos de Siniestros"))

    def login(self):
        self.lblErrors.setText("")
        userName = self.txtUser.text()
        userPassword = self.txtPassword.text()
        if (userName == None or len(userName) == 0) or (userPassword == None or len(userPassword) == 0):
            self.showAlert("Usuario y/o contraseña incorrecta")
            return

        userData = UserRepository().login(userName=userName, password=userPassword)
        if userData == None:
            self.showAlert("Usuario y/o contraseña incorrecta")
            return
        self.openWindow(userData=userData)
        self.loginWindow.hide()

    def showAlert(self, text):
        self.lblErrors.setText(text)

    def openWindow(self, userData):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HomeWindow(
            userData=userData)
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginWindow = QtWidgets.QMainWindow()
    ui = Ui_loginWindow()
    ui.setupUi(loginWindow)
    loginWindow.show()
    sys.exit(app.exec())
